### ISSUE TITLE
Improvement suggestion and bug

### ISSUE THREAD

**Issue by flynnridercode** [BeamlakAschalew/flixquest#59]
### Steps to reproduce

Use the app

### Expected behavior

The cache should be less

### Actual behavior

The cache is 6gb

### Android version

Android 14

### Other details

The cache is too high and does not load tv series when it is too high 
Next suggestion:Add now watching sectionon the home page 
Next suggestion:make it so that the next episode can be played directly from the player like in Netflix
Next suggestion: Make 5he episode selection menu like Netflix as the current selector is a bit hard to use and confusing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by BeamlakAschalew** [comment]
I made the cache higher to accomodate users with lower internet speed and to make the player smoother, I'm gonna add a clear cache functionality in settings.
