### ISSUE TITLE
🏷️: GitHub Tag Doesn't Match App Version

### ISSUE THREAD

**Issue by DarkCrypt** [BeamlakAschalew/flixquest#64]
GitHub tag, v2.4.5-2, differs from the release, v2.5.0-2, on the releases page.

I brought this to attention because I've been using Obtainium to update apps and it thinks this version is a downgrade because of the tag.

**Comment by BeamlakAschalew** [comment]
I made a typo, it is now fixed.

**Comment by DarkCrypt** [comment]
Sweet, thank you!
